<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://relaxng.org/ns/structure/1.0"
         xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0"
         datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes"
         ns="https://archivists.org/ns/eaf/v1">
   <include href="modules/attributes.rng"/>
   <include href="modules/datatypes.rng"/>
   <include href="modules/control.rng"/>
   <include href="modules/eaf-identity.rng"/>
   <include href="modules/eaf-description.rng"/>
   <include href="modules/relations.rng/"/>
   <include href="modules/models-and-shared-elements.rng/"/>
   <start>
      <ref name="element.eaf"/>
   </start>
   <define name="element.eaf">
      <element name="eaf">
         <ref name="attribute-group.document-node"/>
         <ref name="element.control"/>
         <ref name="element.functionsDescription"/>
      </element>
   </define>
   <define name="element.functionsDescription">
      <element name="functionsDescription">
         <ref name="attribute-group.global-plus-lang-and-script.optional"/>
         <ref name="attribute-group.assertion-reference.optional"/>
         <ref name="attribute.functionStatus.optional"/>
         <ref name="element.identity"/>
         <optional>
            <ref name="element.description"/>
         </optional>
         <optional>
            <ref name="element.relations"/>
         </optional>
      </element>
   </define>
</grammar>
